// Shruhi Collections (www.shruhicollections.in) — Official 4K Digital Lookbook & WhatsApp Priced Catalog Data
// Includes all 19 original 4K branded plates + all 12 newly priced WhatsApp catalog plates (31 4K plates total)
// with exact MRP (₹850 – ₹3,550), Size Range, and Set Quantity details extracted from WhatsApp Web (+91 884 960 1725).

window.SHRUHI_WHATSAPP_PRICE_LIST = [
  { msgNo: 1, time: "08:20", code: "D.NO 1042 (Crimson Bandhani)", rawMrp: "M R P 2550", rawSize: "SIZE_3XL TO 6XL", price: 2550, priceFormatted: "₹2,550", sizes: ["3XL", "4XL", "5XL", "6XL"], setQty: "4 Pcs Set (3XL–6XL)", image: "assets/products/wa-01-dno-1042-crimson-bandhani-plus.jpg" },
  { msgNo: 2, time: "08:21", code: "SHRUHI ANUPAMA-I (Cinnamon Rust)", rawMrp: "MRP 2550", rawSize: "Size _M to 5xL", price: 2550, priceFormatted: "₹2,550", sizes: ["M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], setQty: "7 Pcs Set (M–5XL)", image: "assets/products/wa-02-shruhi-anupama-rust-suit.jpg" },
  { msgNo: 3, time: "08:22", code: "SHRUHI GLORY (Taupe Beige)", rawMrp: "MRP_2650", rawSize: "SIZE_M TO 2XL", price: 2650, priceFormatted: "₹2,650", sizes: ["M", "L", "XL", "2XL"], setQty: "4 Pcs Set (M–2XL)", image: "assets/products/wa-03-shruhi-glory-taupe-suit.jpg" },
  { msgNo: 4, time: "08:23", code: "SHRUHI GALAXY (Ivory & Crimson Banarasi)", rawMrp: "MRp_3550", rawSize: "M to XL5", price: 3550, priceFormatted: "₹3,550", sizes: ["M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], setQty: "7 Pcs Set (M–5XL)", image: "assets/products/wa-04-shruhi-galaxy-banarasi-suit.jpg" },
  { msgNo: 5, time: "08:24", code: "SHRUHI 5601 (Indigo Denim Midi Dress)", rawMrp: "MRP, 1550", rawSize: "M TO 2XL", price: 1550, priceFormatted: "₹1,550", sizes: ["M", "L", "XL", "2XL"], setQty: "4 Pcs Set (M–2XL)", image: "assets/products/wa-05-shruhi-5601-denim-midi-dress.jpg" },
  { msgNo: 6, time: "08:25", code: "SHRUHI SHREE (Coffee Brown Elegance)", rawMrp: "MRP 2550", rawSize: "Size_M TO 2XXL", price: 2550, priceFormatted: "₹2,550", sizes: ["M", "L", "XL", "2XL"], setQty: "4 Pcs Set (M–2XL)", image: "assets/products/wa-06-shruhi-shree-coffee-suit.jpg" },
  { msgNo: 7, time: "08:26", code: "SHRUHI ANUPAMA-II (Pearl Ivory)", rawMrp: "MRP 2550", rawSize: "Size 3xl to 5xl", price: 2550, priceFormatted: "₹2,550", sizes: ["3XL", "4XL", "5XL"], setQty: "3 Pcs Set (3XL–5XL)", image: "assets/products/wa-07-shruhi-anupama-ivory-suit.jpg" },
  { msgNo: 8, time: "08:27", code: "D.NO 1002 (Mustard Gold Plus Co-ord)", rawMrp: "MRP 1500", rawSize: "SIZE 3XL.4XL", price: 1500, priceFormatted: "₹1,500", sizes: ["3XL", "4XL"], setQty: "2 Pcs Set (3XL, 4XL)", image: "assets/products/wa-08-dno-1002-mustard-plus-coord.jpg" },
  { msgNo: 9, time: "08:28", code: "D.NO 1002 (Ivory Crimson Plus Co-ord)", rawMrp: "MRP 1500", rawSize: "Size 3xL to 5xl", price: 1500, priceFormatted: "₹1,500", sizes: ["3XL", "4XL", "5XL"], setQty: "3 Pcs Set (3XL–5XL)", image: "assets/products/wa-09-dno-1002-ivory-plus-coord.jpg" },
  { msgNo: 10, time: "08:29", code: "SHRUHI 5795 (Maroon Floral Midi Dress)", rawMrp: "MRP-1350", rawSize: "Size_L", price: 1350, priceFormatted: "₹1,350", sizes: ["L"], setQty: "Single Size (L)", image: "assets/products/wa-10-shruhi-5795-floral-midi-dress.jpg" },
  { msgNo: 11, time: "08:30", code: "SHRUHI 5620 (Abstract Swirl Tunic Top)", rawMrp: "MRP_850", rawSize: "SIZE M TO 2XL", price: 850, priceFormatted: "₹850", sizes: ["M", "L", "XL", "2XL"], setQty: "4 Pcs Set (M–2XL)", image: "assets/products/wa-11-shruhi-5620-swirl-tunic.jpg" },
  { msgNo: 12, time: "08:31", code: "SHRUHI KAVYA (Mauve & Ivory Dupatta Suit)", rawMrp: "MRP_2850", rawSize: "Size_S.L.2xl", price: 2850, priceFormatted: "₹2,850", sizes: ["S", "L", "2XL"], setQty: "3 Pcs Set (S, L, 2XL)", image: "assets/products/wa-12-shruhi-kavya-mauve-suit.jpg" }
];

window.SHRUHI_CATALOG = [
  {
    id: "meera-plus-suit",
    code: "MEERA",
    lineGroup: "PLUS",
    name: "Meera Mustard Zari-Yoke Plus-Size Suit Set",
    brandLine: "Shruhi Collections • Curvy Couture",
    category: "suit-sets",
    categoryLabel: "3-Piece Suit Set",
    isPlusSize: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "M R P 2550 | SIZE_3XL TO 6XL",
    qtyInfo: "4 Pcs Set (3XL–6XL)",
    sizes: ["3XL", "4XL", "5XL", "6XL"],
    colorName: "Mustard Olive Gold",
    colorHex: "#9A8B18",
    fabric: "Festive Silk Blend with Woven Dupatta",
    workType: "Geometric & Floral Thread-Zari Neckline Yoke",
    silhouette: "Straight-Cut Kurti with Straight Pants & Dupatta",
    occasion: "Festive & Family Gatherings",
    tagline: "Plus-size elegance in luminous mustard-olive silk blend",
    description:
      "A regal mustard-olive 3-piece ethnic ensemble by Shruhi Collections tailored specifically for curvy silhouettes (3XL to 6XL). Features a richly embroidered square neckline yoke paired with sleek trousers and a statement ethnic-printed border dupatta.",
    highlights: [
      "MRP ₹2,550 • Dedicated Plus-Size grading: 3XL to 6XL (4 Pcs Set)",
      "Intricate square geometric & floral embroidered front yoke",
      "Three-quarter sleeves with notched cuff slits",
      "Full-length patterned ethnic border & mandala pallu dupatta"
    ],
    image: "assets/products/meera-mustard-plus-size-suit.jpg",
    gallery: ["assets/products/meera-mustard-plus-size-suit.jpg"]
  },
  {
    id: "astha-maroon-aline",
    code: "ASTHA",
    lineGroup: "BOUTIQUE",
    name: "Astha Deep Maroon A-Line Tunic & Pant Set",
    brandLine: "Shruhi Collections • Boutique Series",
    category: "coord-sets",
    categoryLabel: "A-Line Kurti & Pant Set",
    isPlusSize: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size _M to 5xL",
    qtyInfo: "7 Pcs Set (M–5XL)",
    sizes: ["M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colorName: "Deep Maroon & Olive Gold",
    colorHex: "#4D151B",
    fabric: "Textured Chanderi / Slub Silk Blend",
    workType: "Contrast Olive-Green Embroidered Yoke & Zari Cuffs",
    silhouette: "Flared A-Line Tunic with Scalloped Hem & Straight Pants",
    occasion: "Evening Wear & Celebrations",
    tagline: "Rich wine-maroon A-line silhouette with contrast olive embroidery",
    description:
      "Designed for refined evening poise by Shruhi Collections, the Astha ensemble pairs a flared A-line deep maroon kurti with tailored straight trousers. A contrasting lime-olive center yoke framed by antique gold geometric embroidery and a scalloped hemline lends heritage artistry.",
    highlights: [
      "MRP ₹2,550 • Extended Size Range: M to 5XL (7 Pcs Set)",
      "Contrast olive-green geometric embroidered bib yoke with pearl drop",
      "Antique gold brocade borders on shoulders and 3/4 sleeve cuffs",
      "Graceful A-line flare with signature scalloped cutwork hem"
    ],
    image: "assets/products/astha-maroon-aline-kurti-set.jpg",
    gallery: ["assets/products/astha-maroon-aline-kurti-set.jpg"]
  },
  {
    id: "styleefik-lamex",
    code: "LAMEX",
    lineGroup: "FESTIVE",
    name: "Lamex Bronze-Gold Scalloped Border Suit Set",
    brandLine: "Shruhi Collections • Festive Couture",
    category: "suit-sets",
    categoryLabel: "3-Piece Festive Suit Set",
    isPlusSize: false,
    price: 2650,
    priceFormatted: "₹2,650",
    rawWhatsAppText: "MRP_2650 | SIZE_M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Antique Bronze Gold",
    colorHex: "#8C6F2D",
    fabric: "Lustrous Tissue-Silk Blend",
    workType: "Silver-Zari Neckline & Vertical Floral Medallion Cutwork",
    silhouette: "Straight Kurti, Ankle Pants & Scalloped Organza Dupatta",
    occasion: "Wedding Guests & Festive Soirées",
    tagline: "Tradition, but make it stylish — Shruhi Collections Festive Edition",
    description:
      "From the Shruhi Collections festive line, Lamex shimmers in an antique bronze-olive hue. Delicate silver-and-maroon floral embroidery graces the rounded neckline and cuffs, while a bold vertical row of circular floral medallions mirrors the scalloped border of the matching dupatta.",
    highlights: [
      "MRP ₹2,650 • Standard Boutique Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Intricate silver-zari & maroon floral neckline and sleeve embroidery",
      "Statement vertical medallion border accent with tassel trim",
      "Matching scalloped-edge dupatta with embroidered floral motifs"
    ],
    image: "assets/products/styleefik-lamex-bronze-suit.jpg",
    gallery: ["assets/products/styleefik-lamex-bronze-suit.jpg"]
  },
  {
    id: "styleefik-tejal",
    code: "TEJAL",
    lineGroup: "FESTIVE",
    name: "Tejal Golden-Ochre V-Neck Palazzo Suit Set",
    brandLine: "Shruhi Collections • Festive Couture",
    category: "suit-sets",
    categoryLabel: "3-Piece Palazzo / Sharara Suit",
    isPlusSize: true,
    price: 3550,
    priceFormatted: "₹3,550",
    rawWhatsAppText: "MRp_3550 | M to XL5",
    qtyInfo: "7 Pcs Set (M–5XL)",
    sizes: ["M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colorName: "Warm Golden Ochre",
    colorHex: "#876118",
    fabric: "Rich Shimmer Silk with Flowing Palazzo",
    workType: "Diamond Medallion Yoke, Sequin Buttis & Scalloped Hem",
    silhouette: "Short V-Neck Kurti with Wide-Leg Flared Palazzo & Dupatta",
    occasion: "Haldi, Mehendi & Festive Occasions",
    tagline: "Tradition, but make it trendy — Shruhi Collections Festive Edition",
    description:
      "Tejal by Shruhi Collections reimagines festive dressing with a sweeping wide-leg palazzo silhouette in warm golden ochre. The V-neck tunic is highlighted by a central diamond-motif embroidered medallion, delicate all-over sequin buttis, and a scalloped dori-embroidered border.",
    highlights: [
      "MRP ₹3,550 • Full Size Range: M to 5XL (7 Pcs Set)",
      "Flattering V-neckline with lime-and-silver diamond motif centerpiece",
      "Scalloped zari cutwork hemline and matching sleeve cuffs",
      "Dramatic wide-leg flared palazzo pants & scalloped dupatta"
    ],
    image: "assets/products/styleefik-tejal-ochre-sharara-set.jpg",
    gallery: ["assets/products/styleefik-tejal-ochre-sharara-set.jpg"]
  },
  {
    id: "moni-pastel-twin",
    code: "MONI",
    lineGroup: "BOUTIQUE",
    name: "Moni Pastel Sage & Ivory Scalloped Dupatta Suit",
    brandLine: "Shruhi Collections • Boutique Series",
    category: "suit-sets",
    categoryLabel: "3-Piece Pastel Suit Set",
    isPlusSize: false,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size_M TO 2XXL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Sage Pastel Green & Ivory Cream",
    colorHex: "#A8B4A5",
    fabric: "Soft Chanderi Cotton-Silk",
    workType: "Burgundy-Rose Resham Embroidery & Cutwork Dupatta",
    silhouette: "Straight Kurti with Tailored Pants & Statement Dupatta",
    occasion: "Daytime Festivities & Pooja",
    tagline: "Serene daytime pastels contrasted with regal berry-wine cutwork",
    description:
      "Showcased in two serene colourways—Mist Sage Green and Pearl Ivory—the Moni 3-piece suit set by Shruhi Collections balances minimalist straight kurtis with opulent burgundy-and-plum embroidered neckline plackets, bold cuff borders, and an heirloom-inspired scalloped archway dupatta.",
    highlights: [
      "MRP ₹2,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Available in dual pastel palettes: Sage Green & Pearl Ivory",
      "Contrast berry-plum embroidered neckline placket and wide cuffs",
      "Statement dupatta with bold scalloped floral-arch borders"
    ],
    image: "assets/products/moni-pastel-twin-suit-set.jpg",
    gallery: ["assets/products/moni-pastel-twin-suit-set.jpg"]
  },
  {
    id: "dno-1042-plus-suit",
    code: "D.NO 1042",
    lineGroup: "PLUS",
    name: "D.No 1042 Olive & Bandhani Print Plus-Size Suit (2-Colour Series)",
    brandLine: "Shruhi Collections • Curvy Couture",
    category: "suit-sets",
    categoryLabel: "3-Piece Plus-Size Suit Set",
    isPlusSize: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "M R P 2550 | SIZE_3XL TO 6XL",
    qtyInfo: "4 Pcs Set (3XL–6XL)",
    sizes: ["3XL", "4XL", "5XL", "6XL"],
    colorName: "Olive Green with Teal / Crimson Dupatta",
    colorHex: "#1E6368",
    fabric: "Soft Viscose Silk with Printed Modal Dupatta",
    workType: "Tie-Up Tassel Neckline & Bandhani / Leaf-Print Dupatta",
    silhouette: "Straight Kurti, Tapered Pants & Contrast Printed Dupatta",
    occasion: "Festive & Smart Casual Ethnic",
    tagline: "Extended curvy sizing (3XL–6XL) with striking Bandhani & botanical dupattas",
    description:
      "Crafted by Shruhi Collections in inclusive sizes 3XL to 6XL (MRP ₹2,550), Design No. 1042 pairs a rich olive-green straight kurta with matching trousers and a contrast dupatta in Teal Botanical Leaf or Crimson Bandhani print.",
    highlights: [
      "WhatsApp Verified: MRP ₹2,550 • Full Plus-Size range: 3XL, 4XL, 5XL, 6XL (4 Pcs Set)",
      "Includes both Teal Leaf & Crimson Bandhani 4K lookbook plates",
      "Embroidered keyhole neckline with handcrafted multicolor tassels",
      "Breathable, flattering straight-cut silhouette with matching pants"
    ],
    image: "assets/products/dno-1042-olive-teal-plus-size-suit.jpg",
    gallery: [
      "assets/products/dno-1042-olive-teal-plus-size-suit.jpg",
      "assets/products/wa-01-dno-1042-crimson-bandhani-plus.jpg"
    ]
  },
  {
    id: "styleefik-kitty-party",
    code: "KITTY PARTY",
    lineGroup: "FESTIVE",
    name: "Kitty Party Mustard Collared Appliqué Co-ord Set",
    brandLine: "Shruhi Collections • Festive Couture",
    category: "coord-sets",
    categoryLabel: "Contemporary Co-ord Set",
    isPlusSize: false,
    price: 1550,
    priceFormatted: "₹1,550",
    rawWhatsAppText: "MRP, 1550 | M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Mustard Ochre",
    colorHex: "#997322",
    fabric: "Crisp Linen-Cotton Slub",
    workType: "Illustrated Fashion-Girl Hem Appliqué & Embroidery",
    silhouette: "Button-Down Shirt Tunic with Straight Trousers",
    occasion: "Brunches, Kitty Parties & Resort Wear",
    tagline: "Playful couture co-ord crafted for daytime soirées",
    description:
      "A conversation-starting contemporary co-ord set by Shruhi Collections. Tailored in earthy mustard-ochre, the collared button-down tunic features whimsical embroidered fashion-figure motifs along the lower hem and pairs effortlessly with matching straight-leg trousers.",
    highlights: [
      "MRP ₹1,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Classic shirt collar with pearl-button front placket",
      "Artistic fashion-sketch appliqué & embroidery across the hemline",
      "Matching straight-fit trousers for a complete one-step outfit"
    ],
    image: "assets/products/styleefik-kitty-party-mustard-coord.jpg",
    gallery: ["assets/products/styleefik-kitty-party-mustard-coord.jpg"]
  },
  {
    id: "styleefik-manika",
    code: "MANIKA",
    lineGroup: "FESTIVE",
    name: "Manika Berry-Mauve Mandala V-Neck Suit Set",
    brandLine: "Shruhi Collections • Festive Couture",
    category: "suit-sets",
    categoryLabel: "3-Piece Suit Set",
    isPlusSize: false,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size_M TO 2XXL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Berry Rose Mauve",
    colorHex: "#9D3B63",
    fabric: "Lustrous Modal / Roman Silk",
    workType: "White & Silver Thread Mandala V-Neck & Scalloped Dupatta",
    silhouette: "Straight V-Neck Kurta, Pants & Tassel Dupatta",
    occasion: "Everyday Elegance & Festive Gatherings",
    tagline: "Style everyday — graceful berry-mauve with crisp white threadwork",
    description:
      "Manika by Shruhi Collections brings together a romantic berry-mauve palette and precision geometric threadwork. The V-neck kurta showcases a striking circular medallion and chevron collar detail, complemented by embroidered cuffs and a scalloped-edge dupatta.",
    highlights: [
      "MRP ₹2,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Statement V-neck with circular chakra/mandala thread embroidery",
      "Matching geometric embroidered cuffs on 3/4 sleeves",
      "Scalloped dupatta with delicate all-over floral buttis & tassels"
    ],
    image: "assets/products/styleefik-manika-mauve-suit.jpg",
    gallery: ["assets/products/styleefik-manika-mauve-suit.jpg"]
  },
  {
    id: "alkapuri-wine-suit",
    code: "ALKAPURI",
    lineGroup: "BOUTIQUE",
    name: "Alkapuri Deep Wine Palazzo & Organza Dupatta Set",
    brandLine: "Shruhi Collections • Boutique Series",
    category: "suit-sets",
    categoryLabel: "3-Piece Palazzo Suit Set",
    isPlusSize: false,
    price: 2650,
    priceFormatted: "₹2,650",
    rawWhatsAppText: "MRP_2650 | SIZE_M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Deep Plum Wine",
    colorHex: "#5D2335",
    fabric: "Roman Silk with Sheer Embroidered Dupatta",
    workType: "Silver Zari Neckline Placket & Floral Motif Dupatta",
    silhouette: "Straight Kurta with Wide-Leg Palazzo & Dupatta",
    occasion: "Evening Receptions & Festive Dinners",
    tagline: "Monochromatic deep plum luxury with silver zari finesse",
    description:
      "Understated luxury defines the Alkapuri deep wine 3-piece suit by Shruhi Collections. The straight-cut tunic features a refined silver-zari neckline and vertical placket with intricately worked sleeve cuffs, paired with relaxed wide-leg palazzos and a lightweight matching dupatta.",
    highlights: [
      "MRP ₹2,650 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Monochromatic deep wine-burgundy palette for timeless appeal",
      "Delicate silver zari embroidery along the neckline and 3/4 cuffs",
      "Comfortable wide-leg palazzo bottoms & embroidered dupatta"
    ],
    image: "assets/products/alkapuri-wine-palazzo-suit.jpg",
    gallery: ["assets/products/alkapuri-wine-palazzo-suit.jpg"]
  },
  {
    id: "dno-1038-plus-suit",
    code: "D.NO 1038",
    lineGroup: "PLUS",
    name: "D.No 1038 Crimson Maroon Geometric Panel Plus-Size Suit",
    brandLine: "Shruhi Collections • Curvy Couture",
    category: "suit-sets",
    categoryLabel: "3-Piece Plus-Size Suit Set",
    isPlusSize: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "M R P 2550 | SIZE_3XL TO 6XL",
    qtyInfo: "4 Pcs Set (3XL–6XL)",
    sizes: ["3XL", "4XL", "5XL", "6XL"],
    colorName: "Crimson Maroon",
    colorHex: "#7A1624",
    fabric: "Premium Heavy Rayon / Silk Blend",
    workType: "Full-Length Ajrakh-Inspired Geometric Center Panel & Mirror Accents",
    silhouette: "Slimming Center-Panel Straight Kurta, Pants & Printed Dupatta",
    occasion: "Festive, Traditional & Cultural Events",
    tagline: "Elongating vertical geometric panel tailored for sizes 3XL to 6XL",
    description:
      "Engineered by Shruhi Collections to flatter curvy figures in sizes 3XL through 6XL (MRP ₹2,550), Design No. 1038 features a bold vertical center panel of heritage geometric tile print accented with real mirror-work highlights, matching trousers, and a full geometric-printed dupatta.",
    highlights: [
      "MRP ₹2,550 • Inclusive Plus-Size range: 3XL, 4XL, 5XL, 6XL (4 Pcs Set)",
      "Vertical geometric tile-print center panel for a slimming silhouette",
      "Subtle mirror-work and sequin highlights along the front panel",
      "Coordinated full-width geometric printed dupatta and maroon pants"
    ],
    image: "assets/products/dno-1038-maroon-ajrakh-plus-size-suit.jpg",
    gallery: ["assets/products/dno-1038-maroon-ajrakh-plus-size-suit.jpg"]
  },
  {
    id: "mostyle-4781-tunic",
    code: "SHRUHI 4781",
    lineGroup: "STUDIO",
    name: "Shruhi 4781 Ivory Floral Lace-Trim Peplum Tunic",
    brandLine: "Shruhi Collections • Studio Fusion",
    category: "tunics-dresses",
    categoryLabel: "Fusion Peplum Tunic Top",
    isPlusSize: false,
    price: 850,
    priceFormatted: "₹850",
    rawWhatsAppText: "MRP_850 | SIZE M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Ivory Multi-Floral",
    colorHex: "#EAE6DF",
    fabric: "Breathable Textured Cotton Lawn",
    workType: "Watercolor Botanical Print, Crochet Lace & Braided Tassel Belt",
    silhouette: "Gathered Peplum Tunic with Tie-Up Neckline",
    occasion: "Daywear, Resort, Office & Casual Outings",
    tagline: "Fresh botanical prints framed with delicate white crochet lace",
    description:
      "Shruhi Code 4781 is a breezy ivory floral fusion top crafted for effortless everyday styling. Features a front keyhole tie-up neckline, pintuck bodice detailing, wide white crochet lace borders at the cuffs and hem, and a detachable green braided waist cord.",
    highlights: [
      "MRP ₹850 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Soft watercolor floral print on textured ivory cotton",
      "Intricate white schiffli/crochet lace border at hem and sleeves",
      "Includes braided botanical-green waist tie with tassel ends"
    ],
    image: "assets/products/mostyle-4781-ivory-floral-tunic.jpg",
    gallery: ["assets/products/mostyle-4781-ivory-floral-tunic.jpg"]
  },
  {
    id: "mostyle-5708-coord",
    code: "SHRUHI 5708",
    lineGroup: "STUDIO",
    name: "Shruhi 5708 Cream & Dusty Rose Strappy Floral Co-ord Set",
    brandLine: "Shruhi Collections • Studio Fusion",
    category: "coord-sets",
    categoryLabel: "Summer Resort Co-ord Set",
    isPlusSize: false,
    price: 1550,
    priceFormatted: "₹1,550",
    rawWhatsAppText: "MRP, 1550 | M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Cream Ivory & Dusty Rose",
    colorHex: "#F2ECE1",
    fabric: "Lightweight Linen-Viscose Blend",
    workType: "Lotus Floral Print & Embroidered Sunburst Medallion",
    silhouette: "Tie-Shoulder Strappy Tunic with Wide-Leg Pants",
    occasion: "Vacation, Resort, Sundowners & Summer Brunch",
    tagline: "Sun-kissed resort co-ord with tie-up shoulders and lotus florals",
    description:
      "Channelling modern resort sophistication, Shruhi Code 5708 pairs a cream strappy tunic—complete with adjustable tie-up shoulder straps and a central embroidered sunburst motif—with matching wide-leg trousers adorned in climbing dusty-rose chrysanthemum blooms.",
    highlights: [
      "MRP ₹1,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Adjustable tie-shoulder spaghetti straps with square neckline",
      "Embroidered golden sunburst medallion at the upper bodice",
      "Coordinated botanical floral placement print on tunic and pants"
    ],
    image: "assets/products/mostyle-5708-cream-floral-coord.jpg",
    gallery: ["assets/products/mostyle-5708-cream-floral-coord.jpg"]
  },
  {
    id: "valentina-magenta-suit",
    code: "VALENTINA",
    lineGroup: "BOUTIQUE",
    name: "Valentina Jamun-Magenta Patola Dupatta Suit Set",
    brandLine: "Shruhi Collections • Boutique Series",
    category: "suit-sets",
    categoryLabel: "3-Piece Heritage Suit Set",
    isPlusSize: false,
    price: 2850,
    priceFormatted: "₹2,850",
    rawWhatsAppText: "MRP_2850 | Size_M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Jamun Magenta Wine",
    colorHex: "#7E234A",
    fabric: "Lustrous Modal Silk with Woven-Look Printed Dupatta",
    workType: "Vertical Pintucks, Mirror Diamond Buttis & Patola Borders",
    silhouette: "Straight Kurta, Tapered Trousers & Geometric Dupatta",
    occasion: "Traditional Festivities & Family Celebrations",
    tagline: "Rich jamun-magenta tailored with heritage Patola-inspired geometry",
    description:
      "Valentina by Shruhi Collections celebrates Gujarat-inspired textile heritage with a rich jamun-magenta straight kurta framed by vertical printed borders, fine pintuck pleats, and diamond mirror-work motifs down the center. Paired with matching cigarette pants and a Patola-style dupatta.",
    highlights: [
      "MRP ₹2,850 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Vertical printed side-framing borders for a tailored look",
      "Center panel with pintuck pleats and diamond mirror-work motifs",
      "Grand geometric & bandhani-inspired printed statement dupatta"
    ],
    image: "assets/products/valentina-magenta-patola-suit.jpg",
    gallery: ["assets/products/valentina-magenta-patola-suit.jpg"]
  },
  {
    id: "lock-brown-deer-suit",
    code: "LOCK",
    lineGroup: "BOUTIQUE",
    name: "Lock Espresso Brown Crimson-Moon & Deer Motif Suit Set",
    brandLine: "Shruhi Collections • Boutique Series",
    category: "suit-sets",
    categoryLabel: "3-Piece Designer Suit Set",
    isPlusSize: false,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size_M TO 2XXL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Espresso Brown & Magenta",
    colorHex: "#3C2722",
    fabric: "Textured Tussar-Linen Silk Blend",
    workType: "Artistic Deer & Crimson Sun Appliqué/Print with Scalloped Dupatta",
    silhouette: "V-Neck Straight Kurta, Wide Pants & Scalloped Dupatta",
    occasion: "Evening Gatherings, Art Events & Festive Dinners",
    tagline: "Contemporary poetic artistry on rich espresso-brown tussar blend",
    description:
      "A standout artistic creation by Shruhi Collections in deep espresso brown, the Lock 3-piece suit set features a magenta-piped V-neckline, vertical silver leaf motifs, and a striking white stag silhouetted against a crimson moon near the hem.",
    highlights: [
      "MRP ₹2,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Signature white stag & crimson-pink moon graphic motif on the hem",
      "Contrast magenta V-neck piping and vertical botanical embroidery",
      "Matching brown dupatta with delicate magenta scalloped border"
    ],
    image: "assets/products/lock-coffee-brown-deer-motif-suit.jpg",
    gallery: ["assets/products/lock-coffee-brown-deer-motif-suit.jpg"]
  },
  {
    id: "mostyle-5810-dress",
    code: "SHRUHI 5810",
    lineGroup: "STUDIO",
    name: "Shruhi 5810 Jet-Black Paisley Border Midi Dress",
    brandLine: "Shruhi Collections • Studio Fusion",
    category: "tunics-dresses",
    categoryLabel: "Indo-Western Midi Dress",
    isPlusSize: false,
    price: 1350,
    priceFormatted: "₹1,350",
    rawWhatsAppText: "MRP-1350 | Size_M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Jet Black & Multicolor",
    colorHex: "#1C1B20",
    fabric: "Soft Rayon Crepe",
    workType: "Vibrant Multicolor Kashmiri Paisley Border & Tassel Waist Belt",
    silhouette: "A-Line Button-Down Midi Dress with Waist Tie",
    occasion: "Evening Outings, Travel & Indo-Western Events",
    tagline: "Dramatic multicolor paisley artistry against a sleek jet-black silhouette",
    description:
      "Shruhi Code 5810 is an effortless one-piece Indo-Western midi dress in classic jet black. Designed with a notched mandarin collar, wooden-style front buttons, three-quarter sleeves, and a braided tassel belt that cinches above a vivid multicolor paisley-embroidered hemline.",
    highlights: [
      "MRP ₹1,350 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Rich multicolor paisley border in coral, teal, gold, and lilac",
      "Flattering A-line midi length—wear as a dress or long tunic",
      "Includes detachable braided black-and-white tassel waist belt"
    ],
    image: "assets/products/mostyle-5810-black-paisley-midi-dress.jpg",
    gallery: ["assets/products/mostyle-5810-black-paisley-midi-dress.jpg"]
  },
  {
    id: "mostyle-b2876-coord",
    code: "SHRUHI B-2876",
    lineGroup: "STUDIO",
    name: "Shruhi B-2876 Burgundy Kashmiri-Floral Embroidered Co-ord",
    brandLine: "Shruhi Collections • Studio Fusion",
    category: "coord-sets",
    categoryLabel: "Embroidered Luxury Co-ord Set",
    isPlusSize: false,
    price: 2850,
    priceFormatted: "₹2,850",
    rawWhatsAppText: "MRP_2850 | Size_M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Deep Burgundy Wine",
    colorHex: "#5C131C",
    fabric: "Premium Velvet-Touch / Heavy Roman Silk",
    workType: "360° Front & Back Multicolor Floral Vine Embroidery",
    silhouette: "Rounded-Hem Tunic with Embroidered Wide-Leg Pants",
    occasion: "Festive Evenings, Cocktail & Winter Celebrations",
    tagline: "All-around Kashmiri floral embroidery across tunic, cuffs & trouser hems",
    description:
      "One of the most opulent ensembles in the Shruhi Collections lookbook, Code B-2876 in deep burgundy-maroon showcases lush multicolor floral vine embroidery across both the front and back curved hemline, sleeve cuffs, and wide-leg trouser ankles.",
    highlights: [
      "MRP ₹2,850 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Full front AND back floral vine embroidery along the apple-cut hem",
      "Coordinated floral embroidered borders on sleeve cuffs and pant hems",
      "Includes two 4K lookbook plates (Full View & Detail View)"
    ],
    image: "assets/products/mostyle-b2876-maroon-embroidered-coord.jpg",
    gallery: [
      "assets/products/mostyle-b2876-maroon-embroidered-coord.jpg",
      "assets/products/mostyle-b2876-maroon-embroidered-coord-closeup.jpg"
    ]
  },
  {
    id: "mostyle-5625-tunic",
    code: "SHRUHI 5625",
    lineGroup: "STUDIO",
    name: "Shruhi 5625 Midnight Navy & Crimson Botanical Short Kurti",
    brandLine: "Shruhi Collections • Studio Fusion",
    category: "tunics-dresses",
    categoryLabel: "Everyday Printed Short Kurti",
    isPlusSize: false,
    price: 850,
    priceFormatted: "₹850",
    rawWhatsAppText: "MRP_850 | SIZE M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Midnight Navy, Crimson & Ochre",
    colorHex: "#23293A",
    fabric: "100% Pure Cambric Cotton",
    workType: "All-Over Heritage Kalamkari-Inspired Botanical Print",
    silhouette: "Tailored Mandarin-Collar Short Kurti / Top",
    occasion: "Workwear, College & Everyday Chic",
    tagline: "Versatile botanical cotton tunic tailored to pair with denim or trousers",
    description:
      "Shruhi Code 5625 combines everyday comfort with rich heritage printmaking. Cut from breathable cotton in midnight navy layered with crimson, mustard, and sage foliage, this tailored hip-length tunic features a neat mandarin collar and three-quarter sleeves.",
    highlights: [
      "MRP ₹850 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Rich multi-tone botanical print in navy, crimson, and mustard gold",
      "Tailored princess-seam fit with mandarin band collar",
      "Breathable all-day cotton ideal for pairing with jeans or palazzos"
    ],
    image: "assets/products/mostyle-5625-navy-botanical-tunic.jpg",
    gallery: ["assets/products/mostyle-5625-navy-botanical-tunic.jpg"]
  },
  {
    id: "mostyle-5041-kaftan",
    code: "SHRUHI 5041",
    lineGroup: "STUDIO",
    name: "Shruhi 5041 Dusty Plum Chevron Kaftan & Palazzo Co-ord",
    brandLine: "Shruhi Collections • Studio Fusion",
    category: "coord-sets",
    categoryLabel: "Kaftan & Palazzo Co-ord Set",
    isPlusSize: false,
    price: 1550,
    priceFormatted: "₹1,550",
    rawWhatsAppText: "MRP, 1550 | M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Dusty Plum & Turquoise Accent",
    colorHex: "#573B58",
    fabric: "Fluid Modal Satin / Muslin Silk",
    workType: "Bandhani-Chevron Print with Turquoise Ethnic Border Trim",
    silhouette: "Asymmetrical Draped Kaftan Top with Wide-Leg Palazzo",
    occasion: "Resort Wear, Destination Weddings & Festive Lounge",
    tagline: "Boho-regal plum chevron kaftan co-ord with vibrant turquoise borders",
    description:
      "Effortless movement meets bohemian royalty in Shruhi Code 5041. This two-piece kaftan co-ord set pairs a relaxed poncho-style V-neck top with sweeping wide-leg palazzos in dusty plum chevron bandhani print, accented by a vibrant turquoise-and-coral border.",
    highlights: [
      "MRP ₹1,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Relaxed asymmetrical kaftan/poncho top that flatters every body type",
      "Intricate plum-and-lavender chevron bandhani-inspired print",
      "Wide-leg palazzo pants for maximum comfort and resort flair"
    ],
    image: "assets/products/mostyle-5041-plum-chevron-kaftan-coord.jpg",
    gallery: ["assets/products/mostyle-5041-plum-chevron-kaftan-coord.jpg"]
  },
  // =========================================================================
  // 11 NEW WHATSAPP-PRICED DESIGNS (EXTRACTED DIRECTLY FROM EDGE WHATSAPP)
  // =========================================================================
  {
    id: "wa-anupama-rust-suit",
    code: "ANUPAMA-I",
    lineGroup: "PLUS",
    name: "Anupama Cinnamon-Rust Embroidered Scallop Dupatta Suit",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "suit-sets",
    categoryLabel: "3-Piece Festive Suit Set",
    isPlusSize: true,
    isWhatsAppPriced: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size _M to 5xL",
    qtyInfo: "7 Pcs Set (M–5XL)",
    sizes: ["M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colorName: "Cinnamon Rust Brown",
    colorHex: "#7E3524",
    fabric: "Lustrous Roman Silk with Scalloped Dupatta",
    workType: "Silver-Zari Neckline, Scattered Buttis & Cutwork Dupatta Border",
    silhouette: "Straight Kurta, Cigarette Pants & Scalloped Border Dupatta",
    occasion: "Festive Gatherings & Wedding Events",
    tagline: "WhatsApp Verified Arrival — Inclusive sizing from M right up to 5XL",
    description:
      "Tailored in a warm cinnamon-rust tone and available across an inclusive M to 5XL size range (MRP ₹2,550), Anupama-I features delicate silver-zari neckline embroidery, scattered motif buttis, and a matching dupatta framed by scalloped cutwork.",
    highlights: [
      "WhatsApp Verified: MRP ₹2,550 • Sizes: M to 5XL (7 Pcs Set)",
      "Intricate embroidered rounded neckline and scattered front buttis",
      "Matching dupatta with ornate scalloped cutwork border",
      "Includes matching straight-fit cigarette trousers"
    ],
    image: "assets/products/wa-02-shruhi-anupama-rust-suit.jpg",
    gallery: ["assets/products/wa-02-shruhi-anupama-rust-suit.jpg"]
  },
  {
    id: "wa-glory-taupe-suit",
    code: "SHRUHI GLORY",
    lineGroup: "FESTIVE",
    name: "Glory Taupe-Beige Organza Floral Dupatta Suit Set",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "suit-sets",
    categoryLabel: "3-Piece Organza Dupatta Suit",
    isPlusSize: false,
    isWhatsAppPriced: true,
    price: 2650,
    priceFormatted: "₹2,650",
    rawWhatsAppText: "MRP_2650 | SIZE_M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Taupe Grey-Beige",
    colorHex: "#968C83",
    fabric: "Soft Shimmer Silk with Printed Organza Dupatta",
    workType: "Zari & Pearl V-Placket Embroidery with Floral Organza Dupatta",
    silhouette: "Straight Kurta, Tailored Pants & Sheer Organza Dupatta",
    occasion: "Daytime Weddings, High Tea & Receptions",
    tagline: "The Grand Lady — sophisticated taupe elegance with floral organza",
    description:
      "From the Shruhi Collections Glory line (MRP ₹2,650, Sizes M to 2XL), this refined taupe-beige 3-piece ensemble pairs a shimmering straight kurta featuring pearl-and-zari neckline embroidery with tailored trousers and a botanical-printed organza dupatta.",
    highlights: [
      "WhatsApp Verified: MRP ₹2,650 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Refined taupe-beige palette with intricate neckline threadwork",
      "Sheer organza dupatta with subtle botanical floral print",
      "Tailored straight trousers for a poised silhouette"
    ],
    image: "assets/products/wa-03-shruhi-glory-taupe-suit.jpg",
    gallery: ["assets/products/wa-03-shruhi-glory-taupe-suit.jpg"]
  },
  {
    id: "wa-galaxy-banarasi-suit",
    code: "SHRUHI GALAXY",
    lineGroup: "FESTIVE",
    name: "Galaxy Ivory & Royal Crimson Banarasi Silk Dupatta Suit",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "suit-sets",
    categoryLabel: "3-Piece Banarasi Bridal/Festive Suit",
    isPlusSize: true,
    isWhatsAppPriced: true,
    price: 3550,
    priceFormatted: "₹3,550",
    rawWhatsAppText: "MRp_3550 | M to XL5",
    qtyInfo: "7 Pcs Set (M–5XL)",
    sizes: ["M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colorName: "Pearl Ivory & Crimson Red",
    colorHex: "#8F181C",
    fabric: "Chanderi Silk Kurta with Heavy Woven Banarasi Dupatta",
    workType: "Crimson Zari Neckline & Heirloom Gold-Zari Banarasi Dupatta",
    silhouette: "Straight Ivory Kurta, Pants & Grand Banarasi Dupatta",
    occasion: "Weddings, Bridal Trousseau & Grand Festivities",
    tagline: "Our flagship bridal-festive showstopper in Ivory & Crimson Banarasi",
    description:
      "The crown jewel of the WhatsApp priced collection (MRP ₹3,550, Sizes M to 5XL), Galaxy contrasts a luminous pearl-ivory straight suit featuring a crimson-and-gold embroidered yoke against a richly woven heirloom crimson Banarasi silk dupatta.",
    highlights: [
      "WhatsApp Verified: MRP ₹3,550 • Inclusive Sizes: M to 5XL (7 Pcs Set)",
      "Contrast crimson-and-gold embroidered neckline placket",
      "Full-length heavy woven crimson & gold Banarasi silk dupatta",
      "Matched with tailored ivory straight trousers"
    ],
    image: "assets/products/wa-04-shruhi-galaxy-banarasi-suit.jpg",
    gallery: ["assets/products/wa-04-shruhi-galaxy-banarasi-suit.jpg"]
  },
  {
    id: "wa-5601-denim-dress",
    code: "SHRUHI 5601",
    lineGroup: "STUDIO",
    name: "Shruhi 5601 Indigo Denim Button-Down Tiered Midi Dress",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "tunics-dresses",
    categoryLabel: "Contemporary Denim Midi Dress",
    isPlusSize: false,
    isWhatsAppPriced: true,
    price: 1550,
    priceFormatted: "₹1,550",
    rawWhatsAppText: "MRP, 1550 | M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Classic Indigo Denim Blue",
    colorHex: "#1D5E83",
    fabric: "Soft Washed Tencel-Denim Chambray",
    workType: "Ombré Washed Pleated Skirt Tier & Shirt Collar Placket",
    silhouette: "Collared Button-Down Bodice with Gathered Tiered Midi Skirt",
    occasion: "Casual Daywear, Travel, Brunch & Resort",
    tagline: "Effortless indigo chambray midi with a flattering tiered flare",
    description:
      "Shruhi Code 5601 (MRP ₹1,550, Sizes M to 2XL) brings contemporary western-fusion ease to the lookbook. Tailored in soft washed indigo denim chambray, it features a crisp shirt collar, cuffed 3/4 sleeves, and a gathered ombré-washed midi skirt tier.",
    highlights: [
      "WhatsApp Verified: MRP ₹1,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Soft, breathable washed Tencel-denim fabric with ombré hem",
      "Structured shirt collar with full front button placket",
      "Flattering waist seam opening into a pleated midi skirt"
    ],
    image: "assets/products/wa-05-shruhi-5601-denim-midi-dress.jpg",
    gallery: ["assets/products/wa-05-shruhi-5601-denim-midi-dress.jpg"]
  },
  {
    id: "wa-shree-coffee-suit",
    code: "SHRUHI SHREE",
    lineGroup: "FESTIVE",
    name: "Shree Coffee-Brown Zari-Yoke Elegance 3-Piece Suit Set",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "suit-sets",
    categoryLabel: "3-Piece Festive Suit Set",
    isPlusSize: false,
    isWhatsAppPriced: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size_M TO 2XXL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Rich Coffee Brown",
    colorHex: "#4E3429",
    fabric: "Lustrous Modal / Chanderi Silk",
    workType: "Antique Gold Zari Neckline Medallion & Embroidered Dupatta",
    silhouette: "Straight Kurta, Tapered Pants & Tassel Dupatta",
    occasion: "Evening Functions & Festive Gatherings",
    tagline: "Rich coffee-brown sophistication with antique gold zari embroidery",
    description:
      "From the Shruhi Shree Elegance series (MRP ₹2,550, Sizes M to 2XL), this deep coffee-brown 3-piece suit features an ornate antique-gold embroidered neckline yoke, scattered shimmer buttis, matching straight pants, and a tassel-trimmed sheer dupatta.",
    highlights: [
      "WhatsApp Verified: MRP ₹2,550 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Ornate antique-gold zari & resham embroidered neckline yoke",
      "Matching sheer coffee-brown dupatta with tassel corners",
      "Tailored straight-fit trousers included"
    ],
    image: "assets/products/wa-06-shruhi-shree-coffee-suit.jpg",
    gallery: ["assets/products/wa-06-shruhi-shree-coffee-suit.jpg"]
  },
  {
    id: "wa-anupama-ivory-suit",
    code: "ANUPAMA-II",
    lineGroup: "PLUS",
    name: "Anupama Pearl-Ivory Scalloped Dupatta Plus-Size Suit",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "suit-sets",
    categoryLabel: "3-Piece Plus-Size Suit Set",
    isPlusSize: true,
    isWhatsAppPriced: true,
    price: 2550,
    priceFormatted: "₹2,550",
    rawWhatsAppText: "MRP 2550 | Size 3xl to 5xl",
    qtyInfo: "3 Pcs Set (3XL–5XL)",
    sizes: ["3XL", "4XL", "5XL"],
    colorName: "Pearl White Ivory",
    colorHex: "#EAE5DC",
    fabric: "Lustrous Roman Silk with Scalloped Dupatta",
    workType: "Subtle Silver-Gold Neckline Work & Cutwork Scalloped Dupatta",
    silhouette: "Straight Kurta, Tapered Pants & Scalloped Dupatta",
    occasion: "Daytime Festivities, Pooja & Sophisticated Soirées",
    tagline: "Serene pearl-ivory elegance tailored for curvy sizes 3XL to 5XL",
    description:
      "The pearl-ivory counterpart in the Anupama curvy couture line (MRP ₹2,550, Sizes 3XL to 5XL). Features a refined silver-and-taupe embroidered rounded neckline, delicate front buttis, matching ivory trousers, and a statement scalloped cutwork dupatta.",
    highlights: [
      "WhatsApp Verified: MRP ₹2,550 • Plus-Size Range: 3XL, 4XL, 5XL (3 Pcs Set)",
      "Graceful monochromatic pearl-ivory palette with metallic embroidery",
      "Heirloom-style scalloped cutwork border along the dupatta",
      "Comfortable straight-cut kurti and matching ivory trousers"
    ],
    image: "assets/products/wa-07-shruhi-anupama-ivory-suit.jpg",
    gallery: ["assets/products/wa-07-shruhi-anupama-ivory-suit.jpg"]
  },
  {
    id: "wa-dno1002-mustard-coord",
    code: "D.NO 1002 (GOLD)",
    lineGroup: "PLUS",
    name: "D.No 1002 Mustard-Gold Geometric Yoke Plus-Size Palazzo Set",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "coord-sets",
    categoryLabel: "Plus-Size Kurta & Palazzo Set",
    isPlusSize: true,
    isWhatsAppPriced: true,
    price: 1500,
    priceFormatted: "₹1,500",
    rawWhatsAppText: "MRP 1500 | SIZE 3XL.4XL",
    qtyInfo: "2 Pcs Set (3XL, 4XL)",
    sizes: ["3XL", "4XL"],
    colorName: "Mustard Ochre & Black-Maroon Yoke",
    colorHex: "#AA7B1B",
    fabric: "Heavy Slub Rayon / Cotton Silk",
    workType: "Contrast Black & Maroon Geometric Patchwork Yoke & Sleeve Cuffs",
    silhouette: "Straight Kurta with Wide-Leg Palazzo Trousers",
    occasion: "Everyday Ethnic, Office & Casual Gatherings",
    tagline: "High-value curvy co-ord in warm mustard with bold geometric yoke",
    description:
      "Design No. 1002 in Mustard Gold (MRP ₹1,500, Sizes 3XL & 4XL) is a smart two-piece plus-size kurta and palazzo set featuring a striking black-and-maroon geometric embroidered bib yoke, matching geometric sleeve cuffs, and relaxed wide-leg palazzo bottoms.",
    highlights: [
      "WhatsApp Verified: MRP ₹1,500 • Plus Sizes: 3XL & 4XL (2 Pcs Set)",
      "Contrast black-and-maroon geometric embroidered front yoke",
      "Coordinated geometric border cuffs on 3/4 sleeves",
      "Paired with comfortable wide-leg mustard palazzo pants"
    ],
    image: "assets/products/wa-08-dno-1002-mustard-plus-coord.jpg",
    gallery: ["assets/products/wa-08-dno-1002-mustard-plus-coord.jpg"]
  },
  {
    id: "wa-dno1002-ivory-coord",
    code: "D.NO 1002 (IVORY)",
    lineGroup: "PLUS",
    name: "D.No 1002 Ivory & Rust Geometric Yoke Plus-Size Palazzo Set",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "coord-sets",
    categoryLabel: "Plus-Size Kurta & Palazzo Set",
    isPlusSize: true,
    isWhatsAppPriced: true,
    price: 1500,
    priceFormatted: "₹1,500",
    rawWhatsAppText: "MRP 1500 | Size 3xL to 5xl",
    qtyInfo: "3 Pcs Set (3XL–5XL)",
    sizes: ["3XL", "4XL", "5XL"],
    colorName: "Cream Ivory & Rust Crimson",
    colorHex: "#F0EAE1",
    fabric: "Heavy Slub Rayon / Cotton Silk",
    workType: "Contrast Rust-Maroon Geometric Yoke & Cuffs",
    silhouette: "A-Line Straight Kurta with Wide-Leg Palazzo Trousers",
    occasion: "Daywear, Office & Festive Casual",
    tagline: "Crisp ivory plus-size palazzo set accented with rust-crimson geometry",
    description:
      "Design No. 1002 in Cream Ivory (MRP ₹1,500, Sizes 3XL to 5XL) pairs a breezy ivory straight kurta featuring a bold rust-and-maroon geometric embroidered center yoke and matching sleeve cuffs with flowing wide-leg ivory palazzo trousers.",
    highlights: [
      "WhatsApp Verified: MRP ₹1,500 • Plus Sizes: 3XL, 4XL, 5XL (3 Pcs Set)",
      "Crisp ivory silhouette with contrast rust-maroon geometric yoke",
      "Matching geometric cuff detailing on three-quarter sleeves",
      "Relaxed wide-leg ivory palazzo pants for all-day comfort"
    ],
    image: "assets/products/wa-09-dno-1002-ivory-plus-coord.jpg",
    gallery: ["assets/products/wa-09-dno-1002-ivory-plus-coord.jpg"]
  },
  {
    id: "wa-5795-floral-dress",
    code: "SHRUHI 5795",
    lineGroup: "STUDIO",
    name: "Shruhi 5795 Crimson & Beige Kalamkari Floral Midi Dress",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "tunics-dresses",
    categoryLabel: "Block-Print A-Line Midi Dress",
    isPlusSize: false,
    isWhatsAppPriced: true,
    price: 1350,
    priceFormatted: "₹1,350",
    rawWhatsAppText: "MRP-1350 | Size_L",
    qtyInfo: "Single Size (L)",
    sizes: ["L"],
    colorName: "Crimson Maroon & Sand Beige",
    colorHex: "#7A2326",
    fabric: "100% Pure Soft Cambric Cotton",
    workType: "All-Over Botanical Floral Block Print & Notched Lapel Collar",
    silhouette: "Collared A-Line Flared Midi Dress",
    occasion: "Resort, Brunch, Vacation & Daywear",
    tagline: "Breezy botanical block-print midi dress with notched resort collar",
    description:
      "Shruhi Code 5795 (MRP ₹1,350, Size L) is a sun-drenched A-line midi dress crafted in breathable cotton with an all-over crimson-and-beige botanical floral print, notched lapel collar, fitted waist pleats, and roll-tab three-quarter sleeves.",
    highlights: [
      "WhatsApp Verified: MRP ₹1,350 • Available Size: L",
      "All-over heritage crimson & sand-beige botanical floral print",
      "Smart notched lapel collar with flattering waist pleats",
      "Breathable pure cotton A-line midi silhouette"
    ],
    image: "assets/products/wa-10-shruhi-5795-floral-midi-dress.jpg",
    gallery: ["assets/products/wa-10-shruhi-5795-floral-midi-dress.jpg"]
  },
  {
    id: "wa-5620-swirl-tunic",
    code: "SHRUHI 5620",
    lineGroup: "STUDIO",
    name: "Shruhi 5620 Multicolor Abstract Marble-Swirl Short Tunic",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "tunics-dresses",
    categoryLabel: "Printed Contemporary Short Kurti",
    isPlusSize: false,
    isWhatsAppPriced: true,
    price: 850,
    priceFormatted: "₹850",
    rawWhatsAppText: "MRP_850 | SIZE M TO 2XL",
    qtyInfo: "4 Pcs Set (M–2XL)",
    sizes: ["M", "L", "XL", "2XL"],
    colorName: "Sage, Mauve & Ochre Marble Swirl",
    colorHex: "#6B6770",
    fabric: "Soft Viscose Lawn / Muslin Blend",
    workType: "Artistic Abstract Botanical & Marble Swirl Print",
    silhouette: "Mandarin-Collar Straight Short Tunic Top",
    occasion: "Workwear, College & Everyday Casual",
    tagline: "Art-house abstract swirl print at an everyday-friendly ₹850 MRP",
    description:
      "Shruhi Code 5620 (MRP ₹850, Sizes M to 2XL) is a contemporary hip-length tunic top featuring an artistic watercolor swirl and foliage print in muted sage, mauve, navy, and gold, finished with a mandarin collar and button placket.",
    highlights: [
      "WhatsApp Verified: MRP ₹850 • Sizes: M, L, XL, 2XL (4 Pcs Set)",
      "Unique abstract marble-swirl and botanical placement print",
      "Neat mandarin collar with front button placket",
      "Pairs effortlessly with black denim or straight trousers"
    ],
    image: "assets/products/wa-11-shruhi-5620-swirl-tunic.jpg",
    gallery: ["assets/products/wa-11-shruhi-5620-swirl-tunic.jpg"]
  },
  {
    id: "wa-kavya-mauve-suit",
    code: "SHRUHI KAVYA",
    lineGroup: "BOUTIQUE",
    name: "Kavya Dusty-Mauve Cutwork Hem & Ivory Organza Dupatta Suit",
    brandLine: "Shruhi Collections • WhatsApp Priced Edition",
    category: "suit-sets",
    categoryLabel: "3-Piece Designer Palazzo Suit",
    isPlusSize: false,
    isWhatsAppPriced: true,
    price: 2850,
    priceFormatted: "₹2,850",
    rawWhatsAppText: "MRP_2850 | Size_S.L.2xl",
    qtyInfo: "3 Pcs Set (S, L, 2XL)",
    sizes: ["S", "L", "2XL"],
    colorName: "Dusty Mauve-Brown & Pearl Ivory",
    colorHex: "#7D5E5B",
    fabric: "Textured Chanderi Silk with Scalloped Organza Dupatta",
    workType: "V-Neck Threadwork, Cutwork Kurta Hem & Ivory Scalloped Dupatta",
    silhouette: "Straight Kurta, Wide-Leg Palazzo & Contrast Ivory Dupatta",
    occasion: "Festive Soirées, Engagements & Boutique Events",
    tagline: "Refined dusty-mauve couture paired with a scalloped pearl-ivory dupatta",
    description:
      "Kavya by Shruhi Collections (MRP ₹2,850, Sizes S, L, 2XL) pairs a dusty mauve-taupe straight kurta featuring geometric V-neck embroidery and an intricate cutwork border hemline with wide-leg palazzos and a contrasting pearl-ivory scalloped organza dupatta.",
    highlights: [
      "WhatsApp Verified: MRP ₹2,850 • Available Sizes: S, L, 2XL (3 Pcs Set)",
      "Embroidered V-neckline and intricate floral cutwork hemline",
      "Contrast pearl-ivory dupatta with scalloped edges and buttis",
      "Matched with comfortable wide-leg mauve-taupe palazzo trousers"
    ],
    image: "assets/products/wa-12-shruhi-kavya-mauve-suit.jpg",
    gallery: ["assets/products/wa-12-shruhi-kavya-mauve-suit.jpg"]
  }
];

// Complete 31-plate archive (every 4K branded catalog sheet in sequence)
window.SHRUHI_ALL_19_PLATES = [
  { plateNo: 1, code: "MEERA (₹2,550 • 3XL-6XL)", productId: "meera-plus-suit", image: "assets/products/meera-mustard-plus-size-suit.jpg" },
  { plateNo: 2, code: "ASTHA (₹2,550 • M-5XL)", productId: "astha-maroon-aline", image: "assets/products/astha-maroon-aline-kurti-set.jpg" },
  { plateNo: 3, code: "LAMEX (₹2,650 • M-2XL)", productId: "styleefik-lamex", image: "assets/products/styleefik-lamex-bronze-suit.jpg" },
  { plateNo: 4, code: "TEJAL (₹3,550 • M-5XL)", productId: "styleefik-tejal", image: "assets/products/styleefik-tejal-ochre-sharara-set.jpg" },
  { plateNo: 5, code: "MONI (₹2,550 • M-2XL)", productId: "moni-pastel-twin", image: "assets/products/moni-pastel-twin-suit-set.jpg" },
  { plateNo: 6, code: "D.NO 1042-I (₹2,550 • 3XL-6XL)", productId: "dno-1042-plus-suit", image: "assets/products/dno-1042-olive-teal-plus-size-suit.jpg" },
  { plateNo: 7, code: "KITTY PARTY (₹1,550 • M-2XL)", productId: "styleefik-kitty-party", image: "assets/products/styleefik-kitty-party-mustard-coord.jpg" },
  { plateNo: 8, code: "MANIKA (₹2,550 • M-2XL)", productId: "styleefik-manika", image: "assets/products/styleefik-manika-mauve-suit.jpg" },
  { plateNo: 9, code: "ALKAPURI (₹2,650 • M-2XL)", productId: "alkapuri-wine-suit", image: "assets/products/alkapuri-wine-palazzo-suit.jpg" },
  { plateNo: 10, code: "D.NO 1038 (₹2,550 • 3XL-6XL)", productId: "dno-1038-plus-suit", image: "assets/products/dno-1038-maroon-ajrakh-plus-size-suit.jpg" },
  { plateNo: 11, code: "SHRUHI 4781 (₹850 • M-2XL)", productId: "mostyle-4781-tunic", image: "assets/products/mostyle-4781-ivory-floral-tunic.jpg" },
  { plateNo: 12, code: "SHRUHI 5708 (₹1,550 • M-2XL)", productId: "mostyle-5708-coord", image: "assets/products/mostyle-5708-cream-floral-coord.jpg" },
  { plateNo: 13, code: "VALENTINA (₹2,850 • M-2XL)", productId: "valentina-magenta-suit", image: "assets/products/valentina-magenta-patola-suit.jpg" },
  { plateNo: 14, code: "LOCK (₹2,550 • M-2XL)", productId: "lock-brown-deer-suit", image: "assets/products/lock-coffee-brown-deer-motif-suit.jpg" },
  { plateNo: 15, code: "SHRUHI 5810 (₹1,350 • M-2XL)", productId: "mostyle-5810-dress", image: "assets/products/mostyle-5810-black-paisley-midi-dress.jpg" },
  { plateNo: 16, code: "SHRUHI B-2876 I (₹2,850)", productId: "mostyle-b2876-coord", image: "assets/products/mostyle-b2876-maroon-embroidered-coord.jpg" },
  { plateNo: 17, code: "SHRUHI B-2876 II (₹2,850)", productId: "mostyle-b2876-coord", image: "assets/products/mostyle-b2876-maroon-embroidered-coord-closeup.jpg" },
  { plateNo: 18, code: "SHRUHI 5625 (₹850 • M-2XL)", productId: "mostyle-5625-tunic", image: "assets/products/mostyle-5625-navy-botanical-tunic.jpg" },
  { plateNo: 19, code: "SHRUHI 5041 (₹1,550 • M-2XL)", productId: "mostyle-5041-kaftan", image: "assets/products/mostyle-5041-plum-chevron-kaftan-coord.jpg" },
  { plateNo: 20, code: "D.NO 1042-II (₹2,550 • 3XL-6XL)", productId: "dno-1042-plus-suit", image: "assets/products/wa-01-dno-1042-crimson-bandhani-plus.jpg" },
  { plateNo: 21, code: "ANUPAMA-I (₹2,550 • M-5XL)", productId: "wa-anupama-rust-suit", image: "assets/products/wa-02-shruhi-anupama-rust-suit.jpg" },
  { plateNo: 22, code: "GLORY (₹2,650 • M-2XL)", productId: "wa-glory-taupe-suit", image: "assets/products/wa-03-shruhi-glory-taupe-suit.jpg" },
  { plateNo: 23, code: "GALAXY (₹3,550 • M-5XL)", productId: "wa-galaxy-banarasi-suit", image: "assets/products/wa-04-shruhi-galaxy-banarasi-suit.jpg" },
  { plateNo: 24, code: "SHRUHI 5601 (₹1,550 • M-2XL)", productId: "wa-5601-denim-dress", image: "assets/products/wa-05-shruhi-5601-denim-midi-dress.jpg" },
  { plateNo: 25, code: "SHREE (₹2,550 • M-2XL)", productId: "wa-shree-coffee-suit", image: "assets/products/wa-06-shruhi-shree-coffee-suit.jpg" },
  { plateNo: 26, code: "ANUPAMA-II (₹2,550 • 3XL-5XL)", productId: "wa-anupama-ivory-suit", image: "assets/products/wa-07-shruhi-anupama-ivory-suit.jpg" },
  { plateNo: 27, code: "D.NO 1002 GOLD (₹1,500 • 3XL-4XL)", productId: "wa-dno1002-mustard-coord", image: "assets/products/wa-08-dno-1002-mustard-plus-coord.jpg" },
  { plateNo: 28, code: "D.NO 1002 IVORY (₹1,500 • 3XL-5XL)", productId: "wa-dno1002-ivory-coord", image: "assets/products/wa-09-dno-1002-ivory-plus-coord.jpg" },
  { plateNo: 29, code: "SHRUHI 5795 (₹1,350 • Size L)", productId: "wa-5795-floral-dress", image: "assets/products/wa-10-shruhi-5795-floral-midi-dress.jpg" },
  { plateNo: 30, code: "SHRUHI 5620 (₹850 • M-2XL)", productId: "wa-5620-swirl-tunic", image: "assets/products/wa-11-shruhi-5620-swirl-tunic.jpg" },
  { plateNo: 31, code: "KAVYA (₹2,850 • S,L,2XL)", productId: "wa-kavya-mauve-suit", image: "assets/products/wa-12-shruhi-kavya-mauve-suit.jpg" }
];
